### PR TITLE
Add a wrapper on errors

### PR DESCRIPTION
**Pull request by nlemoine**
So it can be easier to match common alert styles like Bootstrap, Foundation, etc.

### CODE REVIEW

**Comment by chrisguitarguy** [comment]
I think we probably need to check if there are errors first before outputting the wrapper div.

Can you change the line above:

```php
if (apply_filters("frontend_accounts_show_errors_{$s}", true, $additional)) {
  // ...
}
```

to:

```php
$errors = $this->getErrors();
if (apply_filters("frontend_accounts_show_errors_{$s}", !empty($errors), $additional)) {
  echo '<div class="frontend-accounts-errors">';
  foreach ($errors as $key => $errmsg) {
    // ...
  }
  echo '</div>';
}
```

That way we'll only ouput the wrapper if there are errors present.

**Comment by nlemoine** [comment]
My mistake, I've been to fast on this. Check the last commit, it should be good now.

**Comment by nlemoine** [comment]
Hello @chrisguitarguy, 

Could you merge the PR please?
I also would like to change the way error messages are handled because right now, it's quite not easy to make the difference between error and success messages (they all get the same class).

Thanks!

**Comment by nlemoine** [comment]
Thanks!

**Pull request merged**
